# Generated by Django 6.0.1 on 2026-01-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_device', models.CharField(max_length=100)),
                ('model_device', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('encreption_type', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=50)),
            ],
        ),
    ]
