# Generated by Django 6.0.1 on 2026-01-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tower', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('height', models.FloatField()),
                ('number_antennas', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='antenna',
            name='tower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antennas', to='network_management_app.tower'),
        ),
    ]
