# Generated by Django 6.0.1 on 2026-01-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_management_app', '0002_tower_antenna_tower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='number_antennas',
        ),
    ]
