# Generated by Django 6.0.1 on 2026-01-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management_app', '0004_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antenna',
            old_name='encreption_type',
            new_name='encryption',
        ),
        migrations.AddField(
            model_name='antenna',
            name='ccq',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='channel_width',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='distance',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='essid',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='lan_speed',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='noise',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='number_of_clients',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='operation_mode',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='psk',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='signal',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='status',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antenna',
            name='uptime_hours',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
