# Generated by Django 6.0.1 on 2026-02-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_management_app', '0005_rename_encreption_type_antenna_encryption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='height',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='location',
        ),
    ]
