# Generated by Django 6.0.1 on 2026-02-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management_app', '0006_remove_tower_height_remove_tower_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='number_of_clients',
            field=models.IntegerField(default=0),
        ),
    ]
